version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/client/.next
    env_file:
      - ./client/.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-4000}
      CLIENT_URL: http://localhost:3000
    restart: unless-stopped
