FROM node:23-alpine


WORKDIR /app

COPY package.json yarn.lock ./

COPY server/package.json ./server/

RUN yarn install --frozen-lockfile

COPY . .

WORKDIR /app/server

EXPOSE 4000

CMD ["yarn", "dev"]